---
title: "Homework_4"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
---

```{r setup, include=FALSE}
library(flexdashboard)
library(tidyverse)
library(p8105.datasets)
data("instacart")
data("rest_inspec")
library(plotly)

```

Column {data-width=650}
-----------------------------------------------------------------------

### Have Restaurant Scores Improved Over Time? (No)

```{r}
rest_inspec %>% 
  filter(score >= 0,
         grade == "A" | grade == "B" | grade == "C") %>% 
  sample_n(size = 2000) %>% 
  plot_ly(
    x = ~inspection_date, y = ~score, type = "scatter", mode = "markers",
    color = ~grade, alpha = 0.5)
```

Column {data-width=350}
-----------------------------------------------------------------------

### Frequency of Restaurant Scores by Borough

```{r}
rest_inspec %>% 
  filter(grade == "A" | grade == "B" | grade == "C") %>% 
  sample_n(size = 5000) %>% 
  group_by(boro, grade) %>% 
  plot_ly(x = ~boro, color = ~grade, type = "histogram", colors = "viridis")
```

### Score Distribution of Sweetgreen Restaurants by Borough

```{r}
rest_inspec %>% 
  filter(str_detect(dba, "SWEETGREEN")) %>% 
  filter(score >= 0) %>% 
  group_by(boro, score) %>% 
  plot_ly(y = ~score, color = ~boro, type = "box", colors = "viridis")
```

